<a href="https://colab.research.google.com/github/Abhinayarao/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

*  We can create a NumPy ndarray object by using the array() function.
*  To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray


In [10]:
import numpy as np
a = np.array(('python', 'Sql', 'Excel'))
print(a)
print(type(a))

['python' 'Sql' 'Excel']
<class 'numpy.ndarray'>


In [11]:
#The version string is stored under __version__ attribute.
print(np.__version__)

2.0.2


#Dimensions in Arrays
Dimensions are nothing but writing a data(columns) into array in numpy.The list we have written are columns. It should be in a equal sequence.

For example to change the values in a table we'll write table data(columns) in numpy then we'll apply methods on it.


In [14]:
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(8)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
a = np.array([1,2,3,4], ndmin=4)
print(a)

[[[[1 2 3 4]]]]


Array Indexing

In [21]:
#Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
a = np.array([[1,2,3], [4,5,6]])
print(a[0,2], a[1,2])

3 6


In [29]:
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
d = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,1]]])
print(d[0,1,2])


6


Slicing

In [30]:
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(d[0,2,1])

8


Use the step value to determine the **step** of the slicing

In [34]:
a = np.array([1,2,3,4,5,6])
print(a[0:5:2])

[1 3 5]


2-D slicing

In [35]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[1,0:3])

[4 5 6]


In [36]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [37]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[0:2,2])

[3 6]
