<a href="https://colab.research.google.com/github/Abhinayarao/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

*  We can create a NumPy ndarray object by using the array() function.
*  To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray


In [ ]:
import numpy as np
a = np.array(('python', 'Sql', 'Excel'))
print(a)
print(type(a))

['python' 'Sql' 'Excel']
<class 'numpy.ndarray'>


In [ ]:
#The version string is stored under __version__ attribute.
print(np.__version__)

2.0.2


#Dimensions in Arrays
Dimensions are nothing but writing a data(columns) into array in numpy.The list we have written are columns. It should be in a equal sequence.

For example to change the values in a table we'll write table data(columns) in numpy then we'll apply methods on it.

NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.


In [ ]:

a = np.array(8)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
a = np.array([1,2,3,4], ndmin=4)
print(a)

[[[[1 2 3 4]]]]


Array Indexing

In [ ]:
#Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
a = np.array([[1,2,3], [4,5,6]])
print(a[0,2], a[1,2])

3 6


In [ ]:
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
d = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,1]]])
print(d[0,1,2])


6


Slicing

In [ ]:
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(d[0,2,1])

8


Use the step value to determine the **step** of the slicing

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a[0:5:2])

[1 3 5]


2-D slicing

In [ ]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[1,0:3])

[4 5 6]


In [ ]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[0:2,2])

[3 6]


#Numpy Data Types
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array(['Python', 'Sql', 'Excel'])
c = np.array(['copyi'])
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
<U6
<U5


the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

For i, u, f, S and U we can define size as well.

In [ ]:
a = np.array([1,2,3,4,5,6], dtype = 'S')
print(a)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [ ]:
#'i4' stands for 4-byte (32-bit) signed integer
#So, all values in the array will be stored as 32-bit integers.
a = np.array([1,2,3,4,5,6], dtype = 'i4')
print(a)

[1 2 3 4 5 6]


The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
a = np.array([1.2,5.6,3.3,4.6])
b = a.astype('i')
print(a.dtype)
print(b)
print(b.dtype)

float64
[1 5 3 4]
int32


In [ ]:
a = np.array([1,0,5, -1])
b = a.astype(bool)
print(a.dtype)
print(b)
print(b.dtype)


int64
[ True False  True  True]
bool


#Copy and View
* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.copy()
b[1]='Java'  #changing copied array
print(a)
print(b)

['Python' 'Sql' 'Excel']
['Python' 'Java' 'Excel']


In [ ]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.copy()
a[1]='Java'  #changing original array
print(a)
print(b)

['Python' 'Java' 'Excel']
['Python' 'Sql' 'Excel']


In [ ]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.view()
b[1]='c++'  #changing view array
print(a)
print(b)

['Python' 'c++' 'Excel']
['Python' 'c++' 'Excel']


In [ ]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.view()
a[1]='c'  #changing original array
print(a)
print(b)

['Python' 'c' 'Excel']
['Python' 'c' 'Excel']


Shape of an array

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8], [6,8,9,1]])
print(a.shape)

(3, 4)


In [ ]:
a = np.array([1,2,3,4])
print(a.shape)

(4,)


In [ ]:
a = np.array([1,2,3,4], ndmin = 4)
print(a)
print(a.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


#Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(2,3, 2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Iterating Arrays
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
#Iterating 1-D array
a = np.array([1,2,3,4,5,6])
for i in a:
  print(i)

1
2
3
4
5
6


In [ ]:
##Iterating 2-D array
a = np.array([[1,2,3], [4,5,6]])
for i in a:
  print(i)

[1 2 3]
[4 5 6]


In [ ]:
##Iterating 2-D array
a = np.array([[1,2,3], [4,5,6]])
for i in a:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
##Iterating 3-D array
a = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for i in a:
  for j in i:
    print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [ ]:
##Iterating 3-D array
a = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for i in a:
  for j in i:
    for b in j:
      print(b)

1
2
3
4
5
6
7
8
9
10
11
12


The function **nditer(**) is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration

Iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality

In [ ]:
a = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


We can use **op_dtypes** argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in **nditer(**) we pass **flags=['buffered'].**

In [ ]:
a = np.array([1,2,3,4])
for i in np.nditer(a, flags=['buffered'], op_dtypes = ['S']):
  print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the **ndenumerate()** method can be used for those usecases.

In [ ]:
a = np.array([1,2,3,4])
for idx, i in np.ndenumerate(a):
  print(idx, i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
for idx, i in np.ndenumerate(a):
  print(idx, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
a = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for idx, i in np.ndenumerate(a):
  print(idx, i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


#Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use **array_split(**) for splitting arrays,

In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array_split(a,3)
b

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [5]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array_split(a,4)
b

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [9]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array_split(a,3)
print(b)
print(b[0])
print(b[1])


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]


#Splitting 2-D Arrays

In [11]:
a = np.array([[1,2], [3,4], [5,6],[7,8],[9,10]])
b = np.array_split(a,3)
b

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10]])]

The above returns two 2-D arrays.

We can specify which axis we want to do the split around.

The example below also returns three 2-D arrays, but they are split along the column (axis=1).

In [13]:
a = np.array([[1,2], [3,4], [5,6],[7,8],[9,10]])
b = np.array_split(a,3, axis = 1)
b

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([], shape=(5, 0), dtype=int64)]

An alternate solution is using hsplit() opposite of hstack()

Similar alternates to vstack() and dstack() are available as vsplit() and dsplit()

In [21]:
a = np.array([[1,2], [3,4], [5,6],[7,8],[9,10]])
b = np.hsplit(a,2)
b

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])]

#Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the **where()** method.



In [23]:
a = np.array([1,2,3,4,5,6,1,1])
b = np.where(a == 1)
b

(array([0, 6, 7]),)

we can find indexes where the values are odd or even

In [24]:
a = np.array([1,2,3,4,5,6,1,1])
b = np.where(a%2== 1)
b

(array([0, 2, 4, 6, 7]),)

In [25]:
a = np.array([1,2,3,4,5,6,1,1])
b = np.where(a%2== 0)
b

(array([1, 3, 5]),)

There is a method called **searchsorted()** which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [31]:
a = np.array([3,6,7,8,9])
b = np.searchsorted(a,7)
b

np.int64(2)

By default the left most index is returned, but we can give **side='right'** to return the right most index instead.

In [32]:
a = np.array([3,6,7,8,9])
b = np.searchsorted(a,7, side='right')
b

np.int64(3)

To search for more than one value, use an array with the specified values

In [33]:
a = np.array([3,6,7,8,9])
b = np.searchsorted(a,[2,4,8])
b

array([0, 1, 3])

#Sorting Arrays
Sorting means putting elements in an ordered sequence.
Sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called **sort()**, that will sort a specified array.

In [34]:
a = ([5,3,7,9,2])
print(np.sort(a))

[2 3 5 7 9]


In [35]:
a = ([True,True, False])
print(np.sort(a))

[False  True  True]


In [36]:
a  = (['sql', 'Java', 'Python', 'Excel'])
print(np.sort(a))

['Excel' 'Java' 'Python' 'sql']


In [37]:
a = ([4,7,2], [9,3,7])
print(np.sort(a))

[[2 4 7]
 [3 7 9]]


#Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [40]:
a = np.array([15,16,17,18,19,20])
x = [False,True,False,True,True,True]
b = a[x]
print(b)

[16 18 19 20]


In [47]:
#filter array that will return only even elements from the original array:
a = np.array([15,16,17,18,19,20])
b = a%2 == 0
c = a[b]
c

array([16, 18, 20])

In [44]:
#filter array that will return only values higher than 17:
a = np.array([15,16,17,18,19,20])
b = []
for i in a:
  if i>17:
    b.append(True)
  else:
    b.append(False)
c = a[b]
print(b)
print(c)

[False, False, False, True, True, True]
[18 19 20]


In [43]:
#filter array that will return only even elements from the original array:
a = np.array([15,16,17,18,19,20])
b = []
for i in a:
  if (i%2 == 0):
    b.append(True)
  else:
    b.append(False)
c = a[b]
print(b)
print(c)


[False, True, False, True, False, True]
[16 18 20]


We can print the values from the array where the condition is False (i.e., the elements that were not selected in the original code), you can **invert the boolean mask** and then use it to index the array.


In [53]:
a = np.array([15,16,17,18,19,20])
x = [False,True,False,True,False,True]
x_inverted = np.logical_not(x)
b = a[x_inverted]
print(b)


[15 17 19]
