<a href="https://colab.research.google.com/github/Abhinayarao/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

*  We can create a NumPy ndarray object by using the array() function.
*  To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray


In [2]:
import numpy as np
a = np.array(('python', 'Sql', 'Excel'))
print(a)
print(type(a))

['python' 'Sql' 'Excel']
<class 'numpy.ndarray'>


In [11]:
#The version string is stored under __version__ attribute.
print(np.__version__)

2.0.2


#Dimensions in Arrays
Dimensions are nothing but writing a data(columns) into array in numpy.The list we have written are columns. It should be in a equal sequence.

For example to change the values in a table we'll write table data(columns) in numpy then we'll apply methods on it.

NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.


In [14]:

a = np.array(8)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
a = np.array([1,2,3,4], ndmin=4)
print(a)

[[[[1 2 3 4]]]]


Array Indexing

In [21]:
#Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
a = np.array([[1,2,3], [4,5,6]])
print(a[0,2], a[1,2])

3 6


In [29]:
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
d = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,1]]])
print(d[0,1,2])


6


Slicing

In [30]:
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(d[0,2,1])

8


Use the step value to determine the **step** of the slicing

In [34]:
a = np.array([1,2,3,4,5,6])
print(a[0:5:2])

[1 3 5]


2-D slicing

In [35]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[1,0:3])

[4 5 6]


In [36]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [4]:
a = np.array([[1,2,3,0,9], [4,5,6,7,8]])
print(a[0:2,2])

[3 6]


#Numpy Data Types
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [46]:
a = np.array([1,2,3,4,5,6])
b = np.array(['Python', 'Sql', 'Excel'])
c = np.array(['copyi'])
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
<U6
<U5


the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

For i, u, f, S and U we can define size as well.

In [9]:
a = np.array([1,2,3,4,5,6], dtype = 'S')
print(a)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [22]:
#'i4' stands for 4-byte (32-bit) signed integer
#So, all values in the array will be stored as 32-bit integers.
a = np.array([1,2,3,4,5,6], dtype = 'i4')
print(a)

[1 2 3 4 5 6]


The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [37]:
a = np.array([1.2,5.6,3.3,4.6])
b = a.astype('i')
print(a.dtype)
print(b)
print(b.dtype)

float64
[1 5 3 4]
int32


In [45]:
a = np.array([1,0,5, -1])
b = a.astype(bool)
print(a.dtype)
print(b)
print(b.dtype)


int64
[ True False  True  True]
bool


#Copy and View
* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [49]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.copy()
b[1]='Java'  #changing copied array
print(a)
print(b)

['Python' 'Sql' 'Excel']
['Python' 'Java' 'Excel']


In [52]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.copy()
a[1]='Java'  #changing original array
print(a)
print(b)

['Python' 'Java' 'Excel']
['Python' 'Sql' 'Excel']


In [50]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.view()
b[1]='c++'  #changing view array
print(a)
print(b)

['Python' 'c++' 'Excel']
['Python' 'c++' 'Excel']


In [51]:
a = np.array(['Python', 'Sql', 'Excel'])
b = a.view()
a[1]='c'  #changing original array
print(a)
print(b)

['Python' 'c' 'Excel']
['Python' 'c' 'Excel']


Shape of an array

In [57]:
a = np.array([[1,2,3,4],[5,6,7,8], [6,8,9,1]])
print(a.shape)

(3, 4)


In [58]:
a = np.array([1,2,3,4])
print(a.shape)

(4,)
